"""Load CSV files from data/seeds/ into bronze schema. Generated by 'alf seed'."""
from pathlib import Path

from airflow import DAG
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.operators.python import PythonOperator
from datetime import datetime
from sqlalchemy import create_engine, text

import pandas as pd


def _load_seeds(**context):
    """Load data/seeds/*.csv into bronze; data/seeds/bronze/*.csv into bronze; data/seeds/silver/*.csv into silver."""
    dag_file = Path(__file__).resolve()
    project_root = dag_file.parent.parent
    seeds_dir = project_root / "data" / "seeds"
    if not seeds_dir.exists():
        return
    hook = PostgresHook(postgres_conn_id="postgres_datawarehouse")
    uri = hook.get_uri()
    if uri.startswith("postgres://"):
        uri = "postgresql://" + uri[len("postgres://") :]
    engine = create_engine(uri)
    # Top-level CSVs -> bronze (backward compatible)
    for path in sorted(seeds_dir.glob("*.csv")):
        _load_csv(engine, path, "bronze")
    # data/seeds/bronze/*.csv -> bronze
    bronze_dir = seeds_dir / "bronze"
    if bronze_dir.is_dir():
        for path in sorted(bronze_dir.glob("*.csv")):
            _load_csv(engine, path, "bronze")
    # data/seeds/silver/*.csv -> silver
    silver_dir = seeds_dir / "silver"
    if silver_dir.is_dir():
        for path in sorted(silver_dir.glob("*.csv")):
            _load_csv(engine, path, "silver")
    engine.dispose()


def _load_csv(engine, path, schema):
    table_name = path.stem.lower().replace("-", "_")
    df = pd.read_csv(path)
    # Truncate then append to preserve table structure (SERIAL, etc.) from migrations; if table missing, use replace
    try:
        with engine.connect() as conn:
            conn.execute(text(f"TRUNCATE {schema}.{table_name}"))
            conn.commit()
        if_exists = "append"
    except Exception:
        if_exists = "replace"
    df.to_sql(
        table_name,
        engine,
        schema=schema,
        if_exists=if_exists,
        index=False,
        method="multi",
        chunksize=1000,
    )


with DAG(
    dag_id="00_seeds",
    start_date=datetime(2026, 1, 1),
    schedule_interval=None,
    catchup=False,
    tags=["setup", "seeds"],
) as dag:
    PythonOperator(
        task_id="load_seeds",
        python_callable=_load_seeds,
    )