# Soda 4+ data source config (name, type, connection)
name: postgres_datawarehouse
type: postgres
connection:
  host: postgres
  port: 5432
  user: airflow
  password: airflow
  database: datawarehouse
