"""Scaffold a new model file in config/models/ and generate its migration."""

from pathlib import Path

from airlakeflow.style import secho_info, secho_ok, secho_warn


def _snake(s: str) -> str:
    return s.replace("-", "_").lower()


_TPL_MODEL = '''"""Model: {table} ({layer} layer). Generated by alf new model."""

from airlakeflow.models import Model, Field, layer


@layer("{layer}")
class {class_name}(Model):
    __table__ = "{table}"

    id = Field.serial(primary_key=True)
    # Add your columns, e.g.:
    # entity_id = Field.varchar(50)
    # value = Field.numeric(18, 8)
    created_at = Field.timestamp(default="CURRENT_TIMESTAMP")
    updated_at = Field.timestamp(nullable=False)
'''


def run_new_model(
    name: str,
    layer_name: str,
    project_root: Path,
) -> None:
    """Create a new model file under config/models/."""
    root = Path(project_root).resolve()
    models_dir = root / "config" / "models"
    models_dir.mkdir(parents=True, exist_ok=True)

    class_name = name.strip().replace("-", " ").title().replace(" ", "")
    if not class_name.endswith("Model"):
        class_name = class_name + "Model"
    table = _snake(name)

    content = _TPL_MODEL.format(
        class_name=class_name,
        table=table,
        layer=layer_name,
    )

    module_name = _snake(name).replace(" ", "_")
    filepath = models_dir / f"{module_name}.py"
    filepath.write_text(content, encoding="utf-8")

    secho_ok(f"Model created: config/models/{filepath.name}")
    secho_info(f"  Table: {layer_name}.{table}")

    # Generate migration for the new model (and any other models missing one)
    try:
        from airlakeflow.config import get_migration_driver, load_config
        from airlakeflow.migration_gen import generate_migrations

        cfg = load_config(root)
        driver = get_migration_driver(cfg)
        created = generate_migrations(root, driver=driver)
        if created:
            secho_ok(f"  Migration(s) generated: {len(created)} file(s)")
            for p in created:
                rel = p.relative_to(root) if root in p.parents else p
                secho_info(f"    {rel}")
        else:
            secho_warn("  No new migrations (run 'alf migrations generate' if needed).")
    except Exception as e:
        secho_warn(f"  Migration not generated: {e}. Run 'alf migrations generate' later.")
